In [1]:
import numpy as np

In [5]:
np.array([[3, 6, 9],[12, 15, 18], [21, 24, 27]])

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [7]:
data = np.array([[3, 6, 9],[12, 15, 18], [21, 24, 27]])

In [8]:
data

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [27]:
#값 출력해보기
print(data[1][1])
print(data[1,1])

print(data[1][1:3])
print(data[1, [1, 2]])

15
15
[15 18]
[15 18]


In [24]:
data[1, [1, 2]]

array([15, 18])

In [33]:
data[[1, 2],:]
data[[1, 2],]

array([[12, 15, 18],
       [21, 24, 27]])

In [29]:
data[[1, 2],[1, 2]]

array([15, 27])

In [32]:
data[1:3,1:3]

array([[15, 18],
       [24, 27]])